accounts/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views as accounts_views
from django.urls.base import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path(r'signup/', accounts_views.signup, name='signup'),
    path(r'login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(r'reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html',
             email_template_name='accounts/password_reset_email.html',
             subject_template_name='accounts/password_reset_subject.txt',
             success_url=reverse_lazy("accounts:password_reset_done")
         ),
         name='password_reset'),
    path(r'reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path(r'reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path(r'reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path(r'settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
                                                                      success_url=reverse_lazy(
                                                                          "accounts:password_change_done")),
         name='password_change'),
    path(r'settings/password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
    path(r'update/', accounts_views.UserUpdateView.as_view(), name='my_account'),
    path(r'admin/', admin.site.urls),
]

manage_employee/urls.py
from django.contrib import admin
from django.urls import path, include
from employee_manager.views import employee_list

urlpatterns = [
    path('', employee_list, name='home'),
    path('admin/', admin.site.urls),
    path('employee/', include('employee_manager.urls', namespace='employee_manager')),
    path('accounts/', include('accounts.urls',  namespace='accounts')),
]

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
      <title>{% block title %}Employee manager{% endblock %}</title>
      <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/app.css' %}">
      {% block stylesheet %}{% endblock %}
  </head>
  <body>
    {% block body %}
   
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mainMenu">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'accounts:my_account' %}">My account</a>
              <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change password</a>
                {% if user.is_superuser or user.is_staff %}
                 <a class="dropdown-item" href="{% url 'admin:login' %}">admin panel</a>
                 {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
            </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}
    </div>
  </div>
</nav>
    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  {% endblock body %}
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>