accounts/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views as accounts_views
from django.urls.base import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path(r'signup/', accounts_views.signup, name='signup'),
    path(r'login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(r'reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html',
             email_template_name='accounts/password_reset_email.html',
             subject_template_name='accounts/password_reset_subject.txt',
             success_url=reverse_lazy("accounts:password_reset_done")
         ),
         name='password_reset'),
    path(r'reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path(r'reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path(r'reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path(r'settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
                                                                      success_url=reverse_lazy(
                                                                          "accounts:password_change_done")),
         name='password_change'),
    path(r'settings/password/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
    path(r'update/', accounts_views.UserUpdateView.as_view(), name='my_account'),
    path(r'admin/', admin.site.urls),
]

employee_manager/urls.py
from django.urls import path
from .views import employee_list, employee_tasks, task_detail, new_task

app_name = 'employee_manager'

urlpatterns = [
    # path('', employee_list, name='home'),
    path('<int:employee_number>/<slug:employee_slug>/tasks/', employee_tasks, name='employee_tasks'),
    path('<int:task_pk>/<slug:task_slug>/', task_detail, name='task_detail'),
    path('<int:employee_pk>/<slug:employee_slug>/new-task/', new_task, name='new_task'),
]

manage_employee/urls.py
from django.contrib import admin
from django.urls import path, include
from employee_manager.views import employee_list

urlpatterns = [
    path('', employee_list, name='home'),
    path('admin/', admin.site.urls),
    path('employee/', include('employee_manager.urls', namespace='employee_manager')),
    path('accounts/', include('accounts.urls',  namespace='accounts')),
]

employee_manager/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import timedelta


# Create your models here.
from unidecode import unidecode


class Work(models.Model):
    work_title = models.CharField(_('Work title'), max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(_('Description'), blank=True, null=True)
    begin_time = models.DateTimeField(_('Begin time'), default=timezone.now, null=False)
    expected_duration = models.DurationField(_('Expected duration'), blank=True, null=True)
    end_time = models.DateTimeField(_('End time'), auto_now=False, blank=True, null=True)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)
    done = models.BooleanField(_('Done'), default=False)

    def __str__(self):
        return self.work_title

    def get_absolute_url(self):
        return reverse('', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.work_title))
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-begin_time']


class Responsibility(models.Model):
    responsibility_name = models.CharField(_('Responsibility'), max_length=150, primary_key=True)
    slug = models.SlugField(max_length=150, unique=True, null=False)
    rank = models.PositiveSmallIntegerField(_('Rank'), unique=True, default=1, blank=True, null=True)
    description = models.TextField(_('Description'), null=False)
    minimum_salary = models.DecimalField(_('Minimum salary'), max_digits=12, decimal_places=2, blank=True, null=True)
    maximum_salary = models.DecimalField(_('Maximum salary'), max_digits=12, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return self.responsibility_name

    def get_absolute_url(self):
        return reverse('responsibility_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.responsibility_name))
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['rank']


class Employee(models.Model):
    class Gender(models.TextChoices):
        No_answer = 'N', 'No answer'
        Male = 'M', 'Male'
        Female = 'F', 'Female'
        Other = 'O', 'Other'

    user = models.OneToOneField(User, verbose_name=_('User'), on_delete=models.DO_NOTHING, blank=True, null=True)
    employee_number = models.PositiveIntegerField(_('Employee number'), primary_key=True)
    first_name = models.CharField(_('First name'), max_length=50, default='')
    last_name = models.CharField(_('Last name'), max_length=100, default='')
    slug = models.SlugField(max_length=152)
    gender = models.CharField(_('Gender'), max_length=1, choices=Gender.choices, default=Gender.No_answer)
    hire_date = models.DateField(_('Hire date'), blank=True, null=True)
    salary = models.DecimalField(_('Salary'), max_digits=12, decimal_places=2, blank=True, null=True)
    responsibilities = models.ManyToManyField(Responsibility, verbose_name=_('Responsibility'), blank=True)
    remark = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def get_absolute_url(self):
        return reverse('employee_detail', kwargs={'slug': self.slug})

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.first_name+' '+self.last_name))
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['hire_date', 'last_name', 'first_name']
        indexes = [models.Index(fields=['last_name', 'first_name']), ]


class Task(models.Model):
    task_name = models.CharField(_('Task name'), max_length=200)
    slug = models.SlugField(max_length=200)
    belong_to_work = models.ForeignKey(Work, verbose_name=_('Belong to work'), on_delete=models.DO_NOTHING, related_name
    ='tasks')
    employee = models.ForeignKey(Employee, verbose_name=_('Employee'), on_delete=models.DO_NOTHING, related_name='tasks')
    description = models.TextField(_('Description'), blank=True, null=True)
    start_time = models.DateTimeField(_('Start time'), default=timezone.now, null=False)
    expected_duration = models.DurationField(_('Expected time'), blank=True, null=True)
    end_time = models.DateTimeField(_('End time'), auto_now=False, blank=True, null=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    updated = models.DateTimeField(_('Updated'), auto_now=True)
    done = models.BooleanField(_('Done'), default=False)

    def __str__(self):
        return self.task_name

    def get_absolute_url(self):
        return reverse('task_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.task_name))
        if self.done:
            if not self.expected_duration and self.end_time:
                self.expected_duration = self.end_time-self.start_time
            elif self.expected_duration and not self.end_time:
                self.end_time = self.start_time + self.expected_duration
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-updated']
        indexes = [models.Index(fields=['task_name']), ]

employee_manager/forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime
from django.forms import ModelChoiceField, NumberInput, DateTimeInput
from .models import Work


class WorkChoiceField(ModelChoiceField):
    """Return work_title as option string """

    def label_from_instance(self, obj):
        return obj.work_title


class TaskForm(forms.Form):
    task_name = forms.CharField()
    belong_to_work = WorkChoiceField(queryset=Work.objects.all())
    description = forms.CharField(widget=forms.Textarea(
        attrs={'rows': 5, 'placeholder': 'A brief description about this task'}
    ),
        max_length=4000, required=False,
        help_text='The max length of the text is 4000.')
    start_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget())
    expected_duration = forms.DurationField(required=False, error_messages={'invalid': 'Please insert a valid format'
                                                                                       'like: days '
                                                                                       'hours:minutes:seconds'})
    end_time = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget(), required=False)
    done = forms.BooleanField(required=False)

employee_manager/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from .models import Work, Task, Employee, Responsibility
from django.db import connection, transaction
from .forms import TaskForm
from django.template.defaultfilters import slugify
from unidecode import unidecode
from django.utils import timezone
from django.db.models import Sum


# Create your views here.
@login_required
def employee_list(request):
    employees = Employee.objects.filter().order_by('employee_number', 'tasks__belong_to_work').annotate(
        total_task_duration=Sum('tasks__expected_duration', distinct=True))
    return render(request, 'employee_manager/employee_list.html', context={'employees': employees})


@login_required
def employee_tasks(request, employee_number, employee_slug):
    employee = get_object_or_404(Employee, employee_number=employee_number)
    tasks = employee.tasks.order_by('-created')
    return render(request, 'employee_manager/employee_detail.html', context={'employee': employee, 'tasks': tasks})


@login_required
def task_detail(request, task_pk, task_slug):
    task = get_object_or_404(Task, pk=task_pk)
    return render(request, 'employee_manager/task_detail.html', context={'task': task})


@login_required
def new_task(request, employee_pk, employee_slug):
    # Each user must be able to create a task for himself except staff user
    request_employee = Employee.objects.filter(employee_number=employee_pk).first()
    if not request.user.is_staff and request.user.id != request_employee.user_id:
        raise PermissionDenied("Custom message")
        return
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TaskForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            task_name = form.cleaned_data['task_name']
            slug = slugify(unidecode(task_name))
            belong_to_work = form.cleaned_data['belong_to_work']
            description = form.cleaned_data['description']
            start_time = form.cleaned_data['start_time']
            expected_duration = form.cleaned_data['expected_duration']
            # if expected_duration:
            #     expected_duration = expected_duration.days * 3600000 + expected_duration.seconds * 1000
            end_time = form.cleaned_data['end_time']
            done = form.cleaned_data['done']
            created = timezone.now()
            updated = timezone.now()
            with connection.cursor() as cursor:
                sql = "INSERT INTO employee_manager_task(task_name, slug, belong_to_work_id, employee_id," \
                      " description, start_time, expected_duration, end_time, done, created, updated) VALUES" \
                      " (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
                values = [task_name, slug, belong_to_work.id, employee_pk, description, start_time, expected_duration,
                          end_time, done, created, updated]
                cursor.execute(sql, values)
                connection.commit()
            # redirect to a new URL:
            return redirect('employee_manager:employee_tasks', employee_pk, employee_slug)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = TaskForm()
    return render(request, 'employee_manager/new_task.html', {'form': form, 'employee_pk': employee_pk,
                                                              'employee_slug': employee_slug})


# TODO This class is under construction
@method_decorator(login_required, name='dispatch')
class TaskUpdateView(UpdateView):
    model = Task
    fields = '__all__'
    template_name = 'employee_manager/edit_task.html'
    pk_url_kwarg = 'task_pk'
    context_object_name = 'task'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(employee_id=self.request.user)

    def form_valid(self, form):
        task = form.save(commit=False)
        task.updated = timezone.now()
        task.save()
        return redirect('employee_manager:employee_tasks', employee_number=task.employee.pk,
                        employee_slug=task.employee.slug)

templates/employee_manager/edit_task.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Edit task{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Employees</a></li>
    <li class="breadcrumb-item"><a href="{% url 'employee_manager:employee_tasks' task.employee.employee_number task.employee.slug %}">{{ task.employee_set.count }}</a></li>
  <li class="breadcrumb-item active">{{ task.task_name }}</li>
  <li class="breadcrumb-item active">Edit task</li>
{% endblock %}

{% block content %}
  <form method="post" class="mb-4" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'employee_manager:employee_tasks' task.employee.employee_number task.employee.slug %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

templates/employee_manager/employee_detail.html
{% extends 'base.html' %}

{% load static %}
{% load gravatar %}

{% block title %}{{ employee.get_full_name }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Employees</a></li>
{#  <li class="breadcrumb-item"><a href="{% url '' topic.board.pk %}">{{ topic.board.name }}</a></li>#}
  <li class="breadcrumb-item active">{{ employee.get_full_name }}  tasks:</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
    <a href="{% url 'employee_manager:new_task' employee.pk employee.slug %}" class="btn btn-primary">New task</a>
    </div>



      <table class="table">
      <thead class="thead-inverse">
      <tr>
        <th>Task number</th>
        <th>Task name</th>
        <th>From work</th>
        <th>Start time</th>
        <th>Expected duration</th>
        <th>End time</th>
        <th>Registered at</th>
        <th>Done</th>
      </tr>
    </thead>
       <tbody>
       {% for task in tasks %}
        <tr>
          <td class="align-middle">
            {{ forloop.counter }}
          </td>
          <td class="align-middle">
            <a href="{% url 'employee_manager:task_detail' task.pk   task.slug %}">{{ task.task_name }}</a>

          </td>
          <td class="align-middle">
            {{ task.belong_to_work }}
          </td>
          <td class="align-middle">
            {{ task.start_time }}
          </td>
          <td class="align-middle">
              {{ task.expected_duration }}
          </td>
          <td class="align-middle">
              {{ task.end_time }}
          </td>
            <td class="align-middle">
              {{ task.created }}
          </td>
          <td class="align-middle">
              {{ task.done }}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{#  {% include 'includes/pagination.html' %}#}
{% endblock %}

templates/employee_manager/employee_list.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Employees</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Employee</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Birth date</th>
        <th>Gender</th>
        <th>Hire date</th>
        <th>Current task</th>
        <th>Latest responsibility</th>
      </tr>
    </thead>
    <tbody>
      {% for employee in employees %}
        <tr>
          <td>
            <a href="{% url 'employee_manager:employee_tasks' employee.employee_number employee.slug %}">{{ employee.get_full_name }}</a>
            <small class="text-muted d-block">{{ employee.employee_number }}</small>
              <small class="text-muted d-block">Total task duration: {{ employee.total_task_duration }}</small>
          </td>
          <td class="align-middle">
            {{ employee.first_name }}
          </td>
          <td class="align-middle">
            {{ employee.last_name }}
          </td>
          <td class="align-middle">
              {{ employee.birth_date }}
          </td>
          <td class="align-middle">
              {{ employee.get_gender_display }}
          </td>
            <td class="align-middle">
              {{ employee.hire_date }}
          </td>
          <td class="align-middle">
              {{ employee.tasks.first }}
          </td>
          <td class="align-middle">
              {{ employee.responsibilities.first }}
          </td>
          <td class="align-middle">
{#            {% with post=board.get_last_post %}#}
{#  {% if post %}#}
{#    <small>#}
{#      <a href="{% url 'topic_posts' board.pk post.topic.pk %}">#}
{#        By {{ post.created_by.username }} at {{ post.created_at }}#}
{#      </a>#}
{#    </small>#}
{#  {% else %}#}
{#    <small class="text-muted">#}
{#      <em>No posts yet.</em>#}
{#    </small>#}
{#  {% endif %}#}
{#{% endwith %}#}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/employee_manager/new_task.html
{% extends 'base.html' %}

{% block title %}Start a New Task{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Employees</a></li>
  <li class="breadcrumb-item"><a href="{% url 'employee_manager:employee_tasks' employee_pk employee_slug%}">{{ employee_slug }}</a></li>
  <li class="breadcrumb-item active">New Task</li>
{% endblock %}

{% block content %}
    <div class="card m-sm-1">
    {% if exception %}
      <p>{{ exception }}</p>
    {% else %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Save</button>
  </form>
    {% endif %}
    </div>
{% endblock %}

templates/employee_manager/task_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ task.task_name }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Employees</a></li>
    <li class="breadcrumb-item"><a href="{% url 'employee_manager:employee_tasks' task.employee.employee_number task.employee.slug %}">{{ task.employee.get_full_name }}</a></li>
  <li class="breadcrumb-item active">{{ task.task_name }}</li>
   <div>

   </div>


{% endblock %}